server:
  port: 8082
spring:
  application:
    name: "reportes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
aws:
  dynamodb:
    endpoint: "http://localhost:8000"
entrypoint:
  sqs:
    region: "${AWS_REGION}"
    queueReport: "${APPROVED_APPLICATION_REPORTS_QUEUE}"
    accessKeyId: "${AWS_ACCESS_KEY_ID}"
    secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
adapters:
  aws:
    dynamodb:
      tableName: "${AWS_DYNAMODB_TABLE_NAME}"
      metricKey: "${AWS_DYNAMODB_METRIC_KEY}"
      region: "${AWS_REGION}"
      accessKeyId: "${AWS_ACCESS_KEY_ID}"
      secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
